"""created-table

Revision ID: 6c65ce351185
Revises: 
Create Date: 2023-06-07 11:52:21.342599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c65ce351185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hangmans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letters', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hangmans')
    # ### end Alembic commands ###
